default_stages: [commit]
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-ast
    - id: debug-statements
    - id: check-toml
    - id: check-json
    - id: check-xml

  - repo: local
    hooks:
      - id: generate typer docs
        name: generate-type-docs
        entry: bash -c 'PYTHONPATH="." typer src/cli/cli.py utils docs --output ./src/cli/README.md && git add ./src/cli/README.md'
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [
          "tests",
          "alembic",
          "src",
          "main.py"
        ]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [
          "--check-only",
          "tests",
          "alembic",
          "src",
          "main.py"
        ]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [
          "tests",
          "src",
          "main.py"
        ]
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        args:
          [
            "-p no:warnings",
            "--cov-fail-under=60",
            "./tests",
          ]
