version: "3.9"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development-api
    # command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5679 -m uvicorn src.api:app --reload --port 8001 --host 0.0.0.0"]
    environment:
      - PORT=8001
      - ENV=local
    ports:
      - 8001:8001
      - 5679:5679
    volumes:
      - ./src/api:/app/src/api
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGPASSWORD: password123
      POSTGRES_DB: hello-world
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@your-site.jp
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  postgres:
  pgadmin:
